version: '3.8'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    env_file:
      - db/.env.dev.db

  web:
    build:
      context: ../
      dockerfile: deploy/web/Dockerfile

    command: sh -c "cd movies_admin && gunicorn --bind 0.0.0.0:8000 config.wsgi:application"

    volumes:
      - local_static:/usr/src/admin_panel/movies_admin/staticfiles
      - ../:/usr/src/app/

    env_file:
      - web/.env.dev.web
    depends_on:
      - postgres

  nginx:
    build:
      context: ../
      dockerfile: deploy/nginx/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - web

volumes:
  postgres_local_data:
    driver_opts:
      type: none
      device: /Users/mikefour/Desktop/pythonProject/yandex_pr_1/docker_data
      o: bind

  local_static:
    driver_opts:
      type: none
      device: ../movies_admin/staticfiles
      o: bind






