version: '3.8'

services:
  postgres:
    image: postgres:13
    volumes:
      - /Users/mikefour/Desktop/pythonProject/yandex_pr_1/docker_data:/var/lib/postgresql/data
    env_file:
      - db/.env.dev.db

  web:
    build:
      context: ../
      dockerfile: deploy/web/Dockerfile

    command: sh -c "cd movies_admin && gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
#    command: python3 movies_admin/manage.py runserver 0.0.0.0:8000

    volumes:
      - ../:/usr/src/app/
      - ../movies_admin/staticfiles:/usr/src/admin_panel/movies_admin/staticfiles

    expose:
      - 8000
    env_file:
      - web/.env.dev.web
    depends_on:
      - postgres

  nginx:
    build:
      context: ../
      dockerfile: deploy/nginx/Dockerfile
#    volumes:
#      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:8000
    depends_on:
      - web


